environment:
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "call %CONDA%\\Scripts\\activate.bat"
  - "conda info"
  - "conda notexistthing"
  - "conda notexistthing &"
  - "ls not going to work"

build: off

test_script:
  - echo
