environment:
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "set PATH=%CONDA%;%CONDA%\\scripts;%PATH%"
#  - "call %CONDA%\\Scripts\\activate.bat"
  - "conda info"
  - "conda notexistthing"
  - "conda notexistthing & exit"
  - "ls not going to work"
  - "echo ok"

build: off

test_script:
  - echo ok2
