language: generic
sudo: false

env:
  global:
    - PIP=pip

jobs:
  include:
    - &default
      before_install: true
      install: true
      script:
        - which $PIP
        - $PIP --version
        - $PIP install param
        - which python
        - python --version

    - <<: *default
      os: osx
      env: PIP=pip3
