language: generic
sudo: false

env:
  global:
    - PYENV_VERSION=3.6  

jobs:
  include:
    - &default
      before_install: true
      install: true
      script:
        - which python
        - python --version      
        - which pip
        - pip --version
        - pip install param

    - <<: *default
      os: osx
      osx_image: xcode9.3

