language: generic
sudo: false
os:
  - linux

_some_common_thing: &_some_common_thing
  before_install: echo "some common thing"

stages:
  - test
  - name: doc
    if (tag =~ ^v(\d+|\.)+[a-z]\d+$) OR (tag =~ ^website$)

jobs:
  include:
    - &default
      <<: *_some_common_thing
      stage: test
      env: THING="default"
      install: true
      script: echo $THING

    - &more_default
      <<: *_some_common_thing
      <<: *default
      stage: doc
      env: THING="more test"
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: hello
          local_dir: .
          on:
            all_branches: true
            tags: true
            condition: $TRAVIS_TAG =~ [0-9]+[a-z][0-9]+$
        - provider: pages
          skip_cleanup: true
          github_token: hello
          local_dir: .  
          on:
            all_branches: true
            tags: true
            condition: $TRAVIS_TAG = website
