language: generic
sudo: false
os:
  - linux

stages:
  - test

env:
  global:
    - DOIT="doit --db-file=$HOME/extracache/.doitdb"

cache:
  directories:
# default travis pip cache...but seems pointless to cache the
# downloaded packages
#    - $HOME/.cache/pip
# (could instead try to cache a pip-created environment)

    - $HOME/miniconda
    - $HOME/extracache

before_cache:
  - rm -rf $HOME/miniconda/pkgs

jobs:
  include:

    - &python_default
      stage: test
      env:
        - DESC="test like pip-using developer"
        - PYENV_VERSION=3.6
      before_install:
        - pip install tox py2venv
      install: true
      script: tox -e py${PYENV_VERSION//./}

    - <<: *python_default
      env:
        - DESC="test like pip-using developer"
        - PYENV_VERSION=2.7

    - &conda_default
      stage: test
      env:
        - DESC="test like conda-using developer"
        - PYENV_VERSION=3.6
      before_install:
        # install doit/pyct and use to install miniconda...
        - pip install pyct && $DOIT install_miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
# using conda-forge results in downgrading conda, but doit not in
# defaults (https://github.com/AnacondaRecipes/aggregate/issues/37)
#        # ...and now install doit/pyct into miniconda
#        - conda install -y -c pyviz/label/dev -c conda-forge pyct
        - $DOIT ci_configure_conda
      install:
        - $DOIT create_env --name=test-environment --python=$PYENV_VERSION
        - source activate test-environment
        - $DOIT conda_develop_install --channel=pyviz/label/dev
      script:
        - conda list


#    - <<: *python_default
#      env:
#        - DESC="test like pip-using developer"
#        - PYENV_VERSION=2.7
#      before_install:
#        - pip install py2venv


#        - echo $PATH
#        - which python
#        - python --version
#        - which pip
#        - pip --version
#        - which pipenv
#        - pipenv --version
#        - which easy_install
#        - easy_install --version
#        - which virtualenv
#        - virtualenv --version
#        #
#        - python -m venv testing123
#        - source testing123/bin/activate
#        - which python
#        - python --version
#        - which pip
#        - pip --version
#
        

#      before_install:
#        - 
#        ## use system python to install doit, then use doit to install miniconda
#        - easy_install --user doit==0.29.0 pyct && ~/.local/bin/doit install_miniconda && rm -f .doit.db
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        ## install doit into miniconda
#        - conda install -y -c pyviz/label/dev -c conda-forge pyct
#        - doit ci_configure_conda
#        
