language: generic
sudo: false

#env:
#  global:
#    - PYENV_VERSION=3.6  

jobs:
  include:
    - &default
      before_install:
        - pyenv --version
        - pyenv versions
      install: true
      script:
        - which python
        - python --version      
        - which pip
        - pip --version
        - pip install param

    - <<: *default
      os: osx
      osx_image: xcode9.3
      before_install:
        - pyenv --version
        - pyenv versions
        - pyenv install 3.6
        - pyenv global 3.6
        - which python
        - python --version
        - which pip
        - pip --version
 #       - pyenv global $PYENV_VERSION
 #       - pyenv rehash
 #       - which python
 #       - python --version
 #       - which pip
 #       - pip --version

