language: generic
sudo: false

env:
  global:
    - PYENV_VERSION=3.6.4

jobs:
  include:
    - &default
      before_install:
        # following 2 lines only required for osx
        - eval "$(pyenv init -)"
        - pyenv install $PYENV_VERSION      
      install: true
      script:
        - which python
        - python --version      
        - which pip
        - pip --version
        - pip install param

    - <<: *default
      os: osx
      osx_image: xcode9.3
#      env: PYENV_VERSION=3.6.4
#      before_install:
#        - eval "$(pyenv init -)"
#        - pyenv install $PYENV_VERSION
