language: generic
sudo: false

#env:
#  global:
#    - PYENV_VERSION=3.6

jobs:
  include:
    - &default
      before_install: true
      install: true
      script: true

#    - <<: *default
#      os: osx
#      osx_image: xcode9.3
#      env: PYENV_VERSION=3.6.4
#      before_install:
#        - eval "$(pyenv init -)"
#        - pyenv install $PYENV_VERSION
