language: generic
sudo: false
os:
  - linux

# quick hack to determine what tag is...
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

stages:
  - test
#  - name: pip_dev_package
#    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
#  - name: pip_package
#    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
#  - name: conda_dev_package
#    if: tag =~ ^v(\d+|\.)*[a-z]\d*$ OR (branch = master AND type != pull_request)
#  - name: conda_package
#    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$

#env:
#  global:
#    - DOIT="doit --db-file=$HOME/extracache/.doitdb"

#cache:
#  directories:
# default travis pip cache...but seems pointless to cache the
# downloaded packages
#    - $HOME/.cache/pip
# (could instead try to cache a pip-created environment)

#    - $HOME/miniconda
#    - $HOME/extracache

#before_cache:
#  - rm -rf $HOME/miniconda/pkgs

jobs:
  include:

#    - &default
#      stage: test
#      install: true
#      script: true
#
#    - <<: *default
#      stage: pip_dev_package
#
#    - <<: *default
#      stage: pip_package
#      
#    - <<: *default
#      stage: conda_dev_package
#
#    - <<: *default
#      stage: conda_package
#

#    - &default
#      stage: test
#      env: PYENV_VERSION=3.6
#      install:
#        - which pyenv
##        - pyenv install 3.7-dev
#      script:
#        - which python
#        - python --version
#        - 
#

#    - <<: *default
#      env: PYENV_VERSION=3.7-dev


    - &python_default
      stage: test
      env:
        - DESC="test like pip-using developer"
        - PYENV_VERSION=3.6
      before_install:
        - pip install tox py2venv
      install:
        - pyenv versions
#
#        - pyenv versions
#        - which python
      script:
        - which python2
#        - which python27
        - which python3
#        - which python36
        - tox -e py27,py36   #py${PYENV_VERSION//./}
        - pyenv global 3.6 2.7
        - tox -e py27,py36   #py${PYENV_VERSION//./}

#    - <<: *python_default
#      env:
#        - DESC="test like pip-using developer"
#        - PYENV_VERSION=2.7
#
#    - &conda_default
#      stage: test
#      env:
#        - DESC="test like conda-using developer"
#        - PYENV_VERSION=3.6
#      before_install:
#        # install doit/pyct and use to install miniconda...
#        - pip install pyct && $DOIT install_miniconda
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        - hash -r
## using conda-forge results in downgrading conda, but doit not in
## defaults (https://github.com/AnacondaRecipes/aggregate/issues/37)...
#        # ...and now install doit/pyct into miniconda
##        - conda install -y -c pyviz/label/dev -c conda-forge pyct
#        # ...so just use pip for now
#        - pip install pyct
#        - $DOIT ci_configure_conda
#      install:
#        - $DOIT create_env --name=test-environment --python=$PYENV_VERSION
#        - source activate test-environment
#        - $DOIT conda_develop_install --channel=pyviz/label/dev
#      script:
#        - conda list
#
##    - <<: *conda_default
##      env:
##        - DESC="test like a conda-using developer"
##        - PYENV_VERSION=2.7
#
#
##    - <<: *python_default
##      env:
##        - DESC="test like pip-using developer"
##        - PYENV_VERSION=2.7
##      before_install:
##        - pip install py2venv
#
#
##        - echo $PATH
##        - which python
##        - python --version
##        - which pip
##        - pip --version
##        - which pipenv
##        - pipenv --version
##        - which easy_install
##        - easy_install --version
##        - which virtualenv
##        - virtualenv --version
##        #
##        - python -m venv testing123
##        - source testing123/bin/activate
##        - which python
##        - python --version
##        - which pip
##        - pip --version
##
#        
#
##      before_install:
##        - 
##        ## use system python to install doit, then use doit to install miniconda
##        - easy_install --user doit==0.29.0 pyct && ~/.local/bin/doit install_miniconda && rm -f .doit.db
##        - export PATH="$HOME/miniconda/bin:$PATH"
##        ## install doit into miniconda
##        - conda install -y -c pyviz/label/dev -c conda-forge pyct
##        - doit ci_configure_conda
##        
#
