language: generic
sudo: false
os:
  - linux

# quick hack to determine what tag is...
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

stages:
  - test
  - name: docs
    if: tag =~ ^v(\d+|\.)

jobs:
  include:
    - &python_default
      stage: test
      before_install: true
      install: true
      script: true

    - stage: docs
      install: true
      script: true
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: x
#          on:
#            tags: true
#            all_branches: true
#            condition: "$TRAVIS_TAG =~ ^v(\d+|\.).*$"
