language: generic
sudo: false
os:
  - linux

stages:
  - test

jobs:
  include:

    - &python_default
      stage: test
      env:
        - DESC="test like pip-using developer"
        - PYENV_VERSION=3.6
      before_install:
        - pip install tox py2venv
      install: true
      script: tox -e py${PYENV_VERSION//./}

    - <<: *python_default
      env:
        - DESC="test like pip-using developer"
        - PYENV_VERSION=2.7

#    - <<: *python_default
#      env:
#        - DESC="test like pip-using developer"
#        - PYENV_VERSION=2.7
#      before_install:
#        - pip install py2venv


#        - echo $PATH
#        - which python
#        - python --version
#        - which pip
#        - pip --version
#        - which pipenv
#        - pipenv --version
#        - which easy_install
#        - easy_install --version
#        - which virtualenv
#        - virtualenv --version
#        #
#        - python -m venv testing123
#        - source testing123/bin/activate
#        - which python
#        - python --version
#        - which pip
#        - pip --version
#
        

#      before_install:
#        - 
#        ## use system python to install doit, then use doit to install miniconda
#        - easy_install --user doit==0.29.0 pyct && ~/.local/bin/doit install_miniconda && rm -f .doit.db
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        ## install doit into miniconda
#        - conda install -y -c pyviz/label/dev -c conda-forge pyct
#        - doit ci_configure_conda
#        
      

#    - &conda_default
#      stage: test
#      env:
#        - DESC="test like conda-using developer"
#        - PYTHON_VERSION=3.6
#      before_install:
#        - easy_install --user doit==0.29.0 pyct && ~/.local/bin/doit install_miniconda && rm -f .doit.db
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        ## install doit into miniconda
#        - conda install -y -c pyviz/label/dev -c conda-forge pyct
#        - doit ci_configure_conda
#      install:
#        - doit create_env --name=test-environment --python=$PYTHON_VERSION
#        - source activate test-environment
#        - doit conda_develop_install --channel=pyviz/label/dev --channel=conda-forge
#      script:
#        - doit all_tests
#