language: generic
sudo: false
os:
  - linux

# quick hack to determine what tag is...
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

stages:
  - test

jobs:
  include:
    - &python_default
      stage: test
      before_install: true
      install: true
      script: true
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: rel
          on:
            tags: true
            all_branches: true
            condition: $TRAVIS_TAG =~ ^v(\d+|\.)*[^a-z]\d*$
        - provider: pages
          skip_cleanup: true
          github_token: dev
          on:
            tags: true
            all_branches: true
            condition: $TRAVIS_TAG =~ ^v(\d+|\.)*[a-z]\d*$
