language: generic
sudo: false
os:
  - linux

_some_common_thing: &_some_common_thing
  before_install: echo "some common thing"

stages:
  - test

jobs:
  include:
    - &default
      <<: *_some_common_thing
      stage: test
      env: THING="default"
      install: true
      script: echo $THING

    - &more_default
      <<: *_some_common_thing
      <<: *default
      env: THING="more test"
